# Generated by Django 5.1.5 on 2025-01-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waiting_time', models.IntegerField(help_text='Waiting time in hours')),
                ('working_hours', models.IntegerField(help_text='Working hours per day')),
                ('phone_number', models.CharField(max_length=15)),
                ('rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.specialty')),
            ],
        ),
    ]
